#!/bin/sh
DIR=~/Bat-Drone-Software
echo "Updating ${DIR}"
git --work-tree ${DIR} checkout -f
cd ${DIR}
echo "Generating build files"
cmake . -DFSW=ON
echo "Compiling"
cd fsw
make -Bj$(( $(nproc --all) + 1)) fsw
echo "Installing"
sudo make install
echo "Starting FSW"
sudo systemctl daemon-reload
#sudo systemctl enable fsw
sudo systemctl restart fsw
systemctl status fsw